name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Cancel previous running workflow in case of a new push
concurrency:
  group: ci-${{ github.head_ref || 'main' }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - run: pnpm install

  check-types:
    runs-on: ubuntu-latest
    needs: ["install"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm check-types

  code-quality:
    runs-on: ubuntu-latest
    needs: ["install"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm format:ci
